export const EXAMS_PERMISSIONS = {
  readiness: {
    read: 'ExamReadiness.Read',
    decide: 'ExamReadiness.Decide',
    evaluate: 'ExamReadiness.Evaluate',
    submitOpinion: 'ExamReadiness.SubmitOpinion',
    readOpinions: 'ExamReadiness.ReadOpinions',
  },
  places: {
    read: 'ExamPlaces.Read',
    manage: 'ExamPlaces.Manage',
    import: 'ExamPlaces.Import',
    watch: 'ExamPlaces.Watch',
  },
  providers: { manage: 'ExamProviders.Manage' },
  registrations: {
    read: 'ExamRegistrations.Read',
    create: 'ExamRegistrations.Create',
    update: 'ExamRegistrations.Update',
    submit: 'ExamRegistrations.Submit',
    resolveErrors: 'ExamRegistrations.ResolveErrors',
  },
  preparation: { read: 'ExamPreparation.Read', manage: 'ExamPreparation.Manage' },
  attempts: { read: 'ExamAttempts.Read', manage: 'ExamAttempts.Manage' },
  results: {
    read: 'ExamResults.Read',
    record: 'ExamResults.Record',
    import: 'ExamResults.Import',
    verify: 'ExamResults.Verify',
    finalize: 'ExamResults.Finalize',
    correct: 'ExamResults.Correct',
  },
  success: { read: 'ExamSuccess.Read', manage: 'ExamSuccess.Manage' },
  failureAnalysis: { read: 'ExamFailureAnalysis.Read', manage: 'ExamFailureAnalysis.Manage' },
  remediation: { read: 'ExamRemediation.Read', manage: 'ExamRemediation.Manage' },
  certifications: {
    read: 'ExamCertifications.Read',
    issue: 'ExamCertifications.Issue',
    revoke: 'ExamCertifications.Revoke',
  },
  analytics: { read: 'ExamAnalytics.Read' },
} as const;
