export const FINANCE_SUPPLIER_INVOICE_PERMISSIONS = {
  read: 'Finance.SupplierInvoices.Read',
  approveOperational: 'Finance.SupplierInvoices.ApproveOperational',
  approveFinancial: 'Finance.SupplierInvoices.ApproveFinancial',
  schedulePayment: 'Finance.SupplierInvoices.SchedulePayment',
  recordManualPayment: 'Finance.SupplierInvoices.RecordManualPayment',
  refundPayment: 'Finance.SupplierInvoices.RefundPayment',
} as const;

export const PROFESSIONAL_MARKETPLACE_PERMISSIONS = {
  dashboard: { read: 'ProfessionalMarketplace.Dashboard.Read' },
  profiles: {
    read: 'ProfessionalMarketplace.Profile.Read',
    create: 'ProfessionalMarketplace.Profile.Create',
    update: 'ProfessionalMarketplace.Profile.Update',
  },
  compliance: {
    read: 'ProfessionalMarketplace.Compliance.Read',
    manage: 'ProfessionalMarketplace.Compliance.Manage',
    verify: 'ProfessionalMarketplace.Compliance.Verify',
  },
  search: { read: 'ProfessionalMarketplace.Search.Read' },
  opportunities: {
    read: 'ProfessionalMarketplace.Opportunities.Read',
    create: 'ProfessionalMarketplace.Opportunities.Create',
    update: 'ProfessionalMarketplace.Opportunities.Update',
    publish: 'ProfessionalMarketplace.Opportunities.Publish',
    pause: 'ProfessionalMarketplace.Opportunities.Pause',
    close: 'ProfessionalMarketplace.Opportunities.Close',
    cancel: 'ProfessionalMarketplace.Opportunities.Cancel',
  },
  invitations: {
    read: 'ProfessionalMarketplace.Invitations.Read',
    create: 'ProfessionalMarketplace.Invitations.Create',
    send: 'ProfessionalMarketplace.Invitations.Send',
    cancel: 'ProfessionalMarketplace.Invitations.Cancel',
    accept: 'ProfessionalMarketplace.Invitations.Accept',
    decline: 'ProfessionalMarketplace.Invitations.Decline',
  },
  applications: {
    read: 'ProfessionalMarketplace.Applications.Read',
    create: 'ProfessionalMarketplace.Applications.Create',
    withdraw: 'ProfessionalMarketplace.Applications.Withdraw',
    review: 'ProfessionalMarketplace.Applications.Review',
    shortlist: 'ProfessionalMarketplace.Applications.Shortlist',
    accept: 'ProfessionalMarketplace.Applications.Accept',
    reject: 'ProfessionalMarketplace.Applications.Reject',
  },
  proposals: {
    read: 'ProfessionalMarketplace.Proposals.Read',
    create: 'ProfessionalMarketplace.Proposals.Create',
    update: 'ProfessionalMarketplace.Proposals.Update',
    send: 'ProfessionalMarketplace.Proposals.Send',
    counter: 'ProfessionalMarketplace.Proposals.Counter',
    accept: 'ProfessionalMarketplace.Proposals.Accept',
    reject: 'ProfessionalMarketplace.Proposals.Reject',
    withdraw: 'ProfessionalMarketplace.Proposals.Withdraw',
  },
  commercialOffers: {
    read: 'ProfessionalMarketplace.CommercialOffers.Read',
    create: 'ProfessionalMarketplace.CommercialOffers.Create',
    counter: 'ProfessionalMarketplace.CommercialOffers.Counter',
    accept: 'ProfessionalMarketplace.CommercialOffers.Accept',
    reject: 'ProfessionalMarketplace.CommercialOffers.Reject',
    withdraw: 'ProfessionalMarketplace.CommercialOffers.Withdraw',
  },
  matching: {
    read: 'ProfessionalMarketplace.Matching.Read',
    run: 'ProfessionalMarketplace.Matching.Run',
    explain: 'ProfessionalMarketplace.Matching.Explain',
  },
  contracts: {
    read: 'ProfessionalMarketplace.Contracts.Read',
    manage: 'ProfessionalMarketplace.Contracts.Manage',
    generate: 'ProfessionalMarketplace.Contracts.Generate',
    sendForSignature: 'ProfessionalMarketplace.Contracts.SendForSignature',
    terminate: 'ProfessionalMarketplace.Contracts.Terminate',
  },
  relationships: {
    read: 'ProfessionalMarketplace.Relationships.Read',
    manage: 'ProfessionalMarketplace.Relationships.Manage',
    activate: 'ProfessionalMarketplace.Relationships.Activate',
    restrict: 'ProfessionalMarketplace.Relationships.Restrict',
    suspend: 'ProfessionalMarketplace.Relationships.Suspend',
    reactivate: 'ProfessionalMarketplace.Relationships.Reactivate',
    terminate: 'ProfessionalMarketplace.Relationships.Terminate',
  },
  missions: {
    read: 'ProfessionalMarketplace.Missions.Read',
    create: 'ProfessionalMarketplace.Missions.Create',
    update: 'ProfessionalMarketplace.Missions.Update',
    propose: 'ProfessionalMarketplace.Missions.Propose',
    accept: 'ProfessionalMarketplace.Missions.Accept',
    decline: 'ProfessionalMarketplace.Missions.Decline',
    activate: 'ProfessionalMarketplace.Missions.Activate',
    pause: 'ProfessionalMarketplace.Missions.Pause',
    complete: 'ProfessionalMarketplace.Missions.Complete',
    cancel: 'ProfessionalMarketplace.Missions.Cancel',
  },
  studentAssignments: {
    read: 'ProfessionalMarketplace.StudentAssignments.Read',
    manage: 'ProfessionalMarketplace.StudentAssignments.Manage',
    revoke: 'ProfessionalMarketplace.StudentAssignments.Revoke',
  },
  accessGrants: {
    read: 'ProfessionalMarketplace.AccessGrants.Read',
    manage: 'ProfessionalMarketplace.AccessGrants.Manage',
    revoke: 'ProfessionalMarketplace.AccessGrants.Revoke',
  },
  serviceEntries: {
    read: 'ProfessionalMarketplace.ServiceEntries.Read',
    record: 'ProfessionalMarketplace.ServiceEntries.Record',
    submit: 'ProfessionalMarketplace.ServiceEntries.Submit',
    approve: 'ProfessionalMarketplace.ServiceEntries.Approve',
    reject: 'ProfessionalMarketplace.ServiceEntries.Reject',
    dispute: 'ProfessionalMarketplace.ServiceEntries.Dispute',
  },
  serviceStatements: {
    read: 'ProfessionalMarketplace.ServiceStatements.Read',
    manage: 'ProfessionalMarketplace.ServiceStatements.Manage',
    submit: 'ProfessionalMarketplace.ServiceStatements.Submit',
    approve: 'ProfessionalMarketplace.ServiceStatements.Approve',
    reject: 'ProfessionalMarketplace.ServiceStatements.Reject',
  },
  disputes: {
    read: 'ProfessionalMarketplace.Disputes.Read',
    open: 'ProfessionalMarketplace.Disputes.Open',
    manage: 'ProfessionalMarketplace.Disputes.Manage',
    resolve: 'ProfessionalMarketplace.Disputes.Resolve',
  },
  invoices: {
    read: 'ProfessionalMarketplace.Invoices.Read',
    request: 'ProfessionalMarketplace.Invoices.Request',
  },
  payments: { read: 'ProfessionalMarketplace.Payments.Read' },
  messages: {
    read: 'ProfessionalMarketplace.Messages.Read',
    send: 'ProfessionalMarketplace.Messages.Send',
  },
  reviews: {
    read: 'ProfessionalMarketplace.Reviews.Read',
    create: 'ProfessionalMarketplace.Reviews.Create',
    respond: 'ProfessionalMarketplace.Reviews.Respond',
    report: 'ProfessionalMarketplace.Reviews.Report',
  },
  moderation: {
    read: 'ProfessionalMarketplace.Moderation.Read',
    manage: 'ProfessionalMarketplace.Moderation.Manage',
    hideContent: 'ProfessionalMarketplace.Moderation.HideContent',
    resolveReport: 'ProfessionalMarketplace.Moderation.ResolveReport',
  },
  analytics: { read: 'ProfessionalMarketplace.Analytics.Read' },
} as const;

export const PROFESSIONAL_MARKETPLACE_NAVIGATION_PERMISSIONS = [
  PROFESSIONAL_MARKETPLACE_PERMISSIONS.dashboard.read,
  PROFESSIONAL_MARKETPLACE_PERMISSIONS.profiles.read,
  PROFESSIONAL_MARKETPLACE_PERMISSIONS.search.read,
  PROFESSIONAL_MARKETPLACE_PERMISSIONS.opportunities.read,
  PROFESSIONAL_MARKETPLACE_PERMISSIONS.missions.read,
  PROFESSIONAL_MARKETPLACE_PERMISSIONS.serviceEntries.read,
  PROFESSIONAL_MARKETPLACE_PERMISSIONS.serviceStatements.read,
  PROFESSIONAL_MARKETPLACE_PERMISSIONS.disputes.read,
  PROFESSIONAL_MARKETPLACE_PERMISSIONS.invoices.read,
  PROFESSIONAL_MARKETPLACE_PERMISSIONS.payments.read,
  PROFESSIONAL_MARKETPLACE_PERMISSIONS.analytics.read,
] as const;
