export const CRM_PERMISSIONS = {
  networks: {
    read: 'Networks.Read',
    manage: 'Networks.Manage',
  },
  dashboard: {
    read: 'Crm.Dashboard.Read',
    tabs: {
      nominal: 'Crm.Dashboard.Tabs.Nominal',
      empty: 'Crm.Dashboard.Tabs.Empty',
      partialData: 'Crm.Dashboard.Tabs.PartialData',
      restrictedFinancial: 'Crm.Dashboard.Tabs.RestrictedFinancial',
      activeFilters: 'Crm.Dashboard.Tabs.ActiveFilters',
      integrationIncident: 'Crm.Dashboard.Tabs.IntegrationIncident',
      loading: 'Crm.Dashboard.Tabs.Loading',
      widgetError: 'Crm.Dashboard.Tabs.WidgetError',
    },
    scopes: {
      branch: 'Crm.Dashboard.Scope.Branch',
      organization: 'Crm.Dashboard.Scope.Organization',
      network: 'Crm.Dashboard.Scope.Network',
    },
    financialRead: 'Crm.Dashboard.Financial.Read',
  },
  leads: {
    read: 'Crm.Leads.Read',
    create: 'Crm.Leads.Create',
    update: 'Crm.Leads.Update',
    assign: 'Crm.Leads.Assign',
    qualify: 'Crm.Leads.Qualify',
    changeStatus: 'Crm.Leads.ChangeStatus',
    markLost: 'Crm.Leads.MarkLost',
    setDormant: 'Crm.Leads.SetDormant',
    reopen: 'Crm.Leads.Reopen',
    referToPartner: 'Crm.Leads.ReferToPartner',
    export: 'Crm.Leads.Export',
    manageSavedViews: 'Crm.Leads.SavedViews.Manage',
    shareSavedViews: 'Crm.Leads.SavedViews.Share',
    bulkManage: 'Crm.Leads.Bulk.Manage',
    tabs: {
      nominal: 'Crm.Leads.Tabs.Nominal',
      empty: 'Crm.Leads.Tabs.Empty',
      noResults: 'Crm.Leads.Tabs.NoResults',
      loading: 'Crm.Leads.Tabs.Loading',
      error: 'Crm.Leads.Tabs.Error',
      partialData: 'Crm.Leads.Tabs.PartialData',
      readOnly: 'Crm.Leads.Tabs.ReadOnly',
      limitedPermission: 'Crm.Leads.Tabs.LimitedPermission',
      duplicates: 'Crm.Leads.Tabs.Duplicates',
      staleData: 'Crm.Leads.Tabs.StaleData',
    },
  },
  activities: {
    read: 'Crm.Activities.Read',
    create: 'Crm.Activities.Create',
    createUnattached: 'Crm.Activities.CreateUnattached',
    attach: 'Crm.Activities.Attach',
    invalidate: 'Crm.Activities.Invalidate',
    syncManage: 'Crm.Activities.Sync.Manage',
    import: 'Crm.Activities.Import',
    internalNotesRead: 'Crm.Activities.InternalNotes.Read',
    internalNotesCreate: 'Crm.Activities.InternalNotes.Create',
    attachmentsUpload: 'Crm.Activities.Attachments.Upload',
    attachmentsRead: 'Crm.Activities.Attachments.Read',
    attachmentsDelete: 'Crm.Activities.Attachments.Delete',
    tabs: {
      nominal: 'Crm.Activities.Tabs.Nominal',
      empty: 'Crm.Activities.Tabs.Empty',
      unattached: 'Crm.Activities.Tabs.Unattached',
      imported: 'Crm.Activities.Tabs.Imported',
      syncError: 'Crm.Activities.Tabs.SyncError',
      readOnly: 'Crm.Activities.Tabs.ReadOnly',
      duplicate: 'Crm.Activities.Tabs.Duplicate',
      loading: 'Crm.Activities.Tabs.Loading',
      partialError: 'Crm.Activities.Tabs.PartialError',
    },
  },
  tasks: {
    read: 'Crm.Tasks.Read',
    create: 'Crm.Tasks.Create',
    complete: 'Crm.Tasks.Complete',
    cancel: 'Crm.Tasks.Cancel',
  },
  assessments: {
    read: 'Crm.Assessments.Read',
    create: 'Crm.Assessments.Create',
    schedule: 'Crm.Assessments.Schedule',
    complete: 'Crm.Assessments.Complete',
    cancel: 'Crm.Assessments.Cancel',
    readAssigned: 'Crm.Assessments.ReadAssigned',
    start: 'Crm.Assessments.Start',
    submit: 'Crm.Assessments.Submit',
    notesCreate: 'Crm.AssessmentNotes.Create',
    result: {
      read: 'Crm.Assessments.Result.Read',
      create: 'Crm.Assessments.Result.Create',
      validate: 'Crm.Assessments.Result.Validate',
      share: 'Crm.Assessments.Result.Share',
    },
  },
  offers: {
    read: 'Crm.Offers.Read',
    create: 'Crm.Offers.Create',
    update: 'Crm.Offers.Update',
    submitForApproval: 'Crm.Offers.SubmitForApproval',
    approve: 'Crm.Offers.Approve',
    send: 'Crm.Offers.Send',
    accept: 'Crm.Offers.Accept',
    reject: 'Crm.Offers.Reject',
    revise: 'Crm.Offers.Revise',
    withdraw: 'Crm.Offers.Withdraw',
    markAccepted: 'Crm.Offers.MarkAccepted',
    markRejected: 'Crm.Offers.MarkRejected',
  },
  conversions: {
    convertToStudent: 'Crm.Conversions.ConvertToStudent',
  },
} as const;
