export interface StudentPedagogyAlert { code: string; severity: string; relatedEntityId?: string | null; }
export interface StudentPedagogyKpi { totalCompetencies: number; requiredCompetencies: number; assessedCompetencies: number; unassessedCompetencies: number; assessmentCoveragePercent: number; requiredAssessmentCoveragePercent: number; assessmentCount: number; levelChangeCount: number; openRemediationPlans: number; completedReviews: number; }
export interface TrainingPathListItem { id: string; studentId: string; curriculumVersionId: string; curriculumCode: string; curriculumName: string; curriculumVersionNumber: number; countryCode: string; licenseCategoryCode: string; trainingMode: string; startDate: string; targetCompletionDate?: string | null; estimatedPracticalHours?: number | null; status: string; createdAtUtc: string; }
export interface TrainingPathMilestone { id: string; code: string; name: string; description?: string | null; order: number; targetDate?: string | null; status: string; completedAtUtc?: string | null; }
export interface TrainingPathDetail extends TrainingPathListItem { curriculumId: string; activatedAtUtc?: string | null; completedAtUtc?: string | null; suspendedAtUtc?: string | null; suspensionReason?: string | null; cancelledAtUtc?: string | null; cancellationReason?: string | null; milestones: TrainingPathMilestone[]; }
export interface LevelDistribution { levelCode: string; competencyCount: number; percentage: number; }
export interface ProgressionModule { moduleId: string; moduleCode: string; moduleName: string; order: number; totalCompetencies: number; requiredCompetencies: number; assessedCompetencies: number; unassessedCompetencies: number; assessmentCount: number; assessmentCoveragePercent: number; requiredAssessmentCoveragePercent: number; currentLevelDistribution: LevelDistribution[]; }
export interface ProgressionCompetency { competencyId: string; moduleId: string; moduleCode: string; competencyCode: string; competencyName: string; isRequired: boolean; order: number; currentLevelCode?: string | null; lastAssessedAtUtc?: string | null; lastAssessorUserId?: string | null; assessmentCount: number; levelChangeCount: number; }
export interface ProgressionTimelineItem { assessmentId: string; competencyId: string; competencyCode: string; competencyName: string; moduleId: string; moduleCode: string; moduleName: string; levelCode: string; previousLevelCode?: string | null; levelChanged: boolean; assessorUserId: string; sourceSessionId?: string | null; comment?: string | null; isVisibleToStudent: boolean; assessedAtUtc: string; recordedAtUtc: string; }
export interface PedagogicalProgression { trainingPathId: string; studentId: string; curriculumVersionId: string; trainingPathStatus: string; totalModules: number; totalCompetencies: number; requiredCompetencies: number; assessedCompetencies: number; assessedRequiredCompetencies: number; unassessedCompetencies: number; assessmentCount: number; levelChangeCount: number; assessmentCoveragePercent: number; requiredAssessmentCoveragePercent: number; firstAssessmentAtUtc?: string | null; lastAssessmentAtUtc?: string | null; currentLevelDistribution: LevelDistribution[]; modules: ProgressionModule[]; competencies: ProgressionCompetency[]; recentTimeline: ProgressionTimelineItem[]; }
export interface PedagogicalReview { id: string; studentId: string; trainingPathId: string; reviewerId: string; reason: string; status: string; findings?: string | null; recommendations?: string | null; estimatedRemainingPracticalHours?: number | null; requestedAtUtc: string; startedAtUtc?: string | null; completedAtUtc?: string | null; cancelledAtUtc?: string | null; cancellationReason?: string | null; }
export interface RemediationTarget { id: string; competencyId: string; objective: string; }
export interface RemediationPlan { id: string; studentId: string; trainingPathId: string; responsibleUserId: string; sourcePedagogicalReviewId?: string | null; recommendation: string; recommendedPracticalHours?: number | null; recommendedSessions?: number | null; reviewDate: string; status: string; planCreatedAtUtc: string; activatedAtUtc?: string | null; completedAtUtc?: string | null; cancelledAtUtc?: string | null; cancellationReason?: string | null; targets: RemediationTarget[]; }
export interface PedagogicalReadinessDecision { id: string; decision: string; rationale: string; conditions?: string | null; reviewerId: string; decidedAtUtc: string; }
export interface PedagogicalReadiness { trainingPathId: string; studentId: string; trainingPathStatus: string; requiredCompetencies: number; evaluatedRequiredCompetencies: number; requiredCoveragePercent: number; openRemediationPlans: number; hasCompletedPedagogicalReview: boolean; recommendation: string; blockers: string[]; latestDecision?: PedagogicalReadinessDecision | null; }
export interface StudentPedagogyOverview { studentId: string; selectedTrainingPathId?: string | null; trainingPaths: TrainingPathListItem[]; trainingPath?: TrainingPathDetail | null; kpis?: StudentPedagogyKpi | null; progression?: PedagogicalProgression | null; readiness?: PedagogicalReadiness | null; reviews: PedagogicalReview[]; remediationPlans: RemediationPlan[]; alerts: StudentPedagogyAlert[]; generatedAtUtc: string; }
