export const CONTRACTS_PERMISSIONS = {
  read: 'Contracts.Read',
  create: 'Contracts.Create',
  generate: 'Contracts.Generate',
  signatoriesManage: 'Contracts.Signatories.Manage',
  signatoriesVerify: 'Contracts.Signatories.Verify',
  signatureSend: 'Contracts.Signature.Send',
  signatureRecord: 'Contracts.Signature.Record',
  activate: 'Contracts.Activate',
  amendmentsManage: 'Contracts.Amendments.Manage',
  amendmentsSignatureRecord: 'Contracts.Amendments.Signature.Record',
  amendmentsApply: 'Contracts.Amendments.Apply',
  suspend: 'Contracts.Suspend',
  terminate: 'Contracts.Terminate',
  complete: 'Contracts.Complete',
  expire: 'Contracts.Expire',
  documentsRead: 'Contracts.Documents.Read',
  documentsUpload: 'Contracts.Documents.Upload',
  documentsArchive: 'Contracts.Documents.Archive',
  auditRead: 'Contracts.Audit.Read',
} as const;
