import { Observable } from 'rxjs';
import {ChangeDetectionStrategy,Component,computed,effect,inject,input,output,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {TranslatePipe,TranslateService} from '@ngx-translate/core';
import {AuthorizationService} from '../../../../core/auth/authorization.service';
import {ApiErrorService} from '../../../../core/errors/api-error.service';
import {AuthService} from '../../../../core/services/auth.service';
import {DriveOsDrawerComponent} from '../../../../shared/ui/drawer/driveos-drawer.component';
import {ProfessionalMarketplaceApiService} from '../../data-access/professional-marketplace-api.service';
import {ProfessionalStudentAssignmentDrawerComponent} from '../professional-student-assignment-drawer/professional-student-assignment-drawer.component';
import {PROFESSIONAL_MARKETPLACE_PERMISSIONS} from '../../domain/professional-marketplace-permissions';
import {CreateProfessionalMissionRequest,ProfessionalMission,ProfessionalVehicleProvisionMode} from '../../models/professional-mission.model';
import {ProfessionalStudentAssignment} from '../../models/professional-student-assignment.model';

@Component({selector:'driveos-professional-mission-drawer',standalone:true,imports:[FormsModule,TranslatePipe,DriveOsDrawerComponent,ProfessionalStudentAssignmentDrawerComponent],templateUrl:'./professional-mission-drawer.component.html',changeDetection:ChangeDetectionStrategy.OnPush})
export class ProfessionalMissionDrawerComponent{
 private readonly api=inject(ProfessionalMarketplaceApiService);private readonly auth=inject(AuthService);private readonly authorization=inject(AuthorizationService);private readonly errors=inject(ApiErrorService);private readonly translate=inject(TranslateService);
 readonly open=input(false);readonly engagementId=input<string|null>(null);readonly missionId=input<string|null>(null);readonly engagementStartsOn=input<string>('');readonly engagementEndsOn=input<string>('');readonly defaultCategories=input<readonly string[]>([]);readonly closeRequested=output<void>();readonly changed=output<void>();
 readonly item=signal<ProfessionalMission|null>(null);readonly loading=signal(false);readonly busy=signal(false);readonly formErrors=signal<readonly string[]>([]);readonly tab=signal<'details'|'schedule'|'students'|'history'>('details');readonly reasonMode=signal<'pause'|'cancel'|null>(null);
 readonly organizationId=computed(()=>this.auth.user()?.organizationId??'');readonly isCreate=computed(()=>!this.missionId());
 readonly canCreate=computed(()=>this.authorization.hasPermission(PROFESSIONAL_MARKETPLACE_PERMISSIONS.missions.create));readonly canUpdate=computed(()=>this.authorization.hasPermission(PROFESSIONAL_MARKETPLACE_PERMISSIONS.missions.update));readonly canPropose=computed(()=>this.authorization.hasPermission(PROFESSIONAL_MARKETPLACE_PERMISSIONS.missions.propose));readonly canActivate=computed(()=>this.authorization.hasPermission(PROFESSIONAL_MARKETPLACE_PERMISSIONS.missions.activate));readonly canPause=computed(()=>this.authorization.hasPermission(PROFESSIONAL_MARKETPLACE_PERMISSIONS.missions.pause));readonly canComplete=computed(()=>this.authorization.hasPermission(PROFESSIONAL_MARKETPLACE_PERMISSIONS.missions.complete));readonly canCancel=computed(()=>this.authorization.hasPermission(PROFESSIONAL_MARKETPLACE_PERMISSIONS.missions.cancel));readonly canReadAssignments=computed(()=>this.authorization.hasPermission(PROFESSIONAL_MARKETPLACE_PERMISSIONS.studentAssignments.read));readonly canManageAssignments=computed(()=>this.authorization.hasPermission(PROFESSIONAL_MARKETPLACE_PERMISSIONS.studentAssignments.manage));
 title='';description='';startsOn='';endsOn='';categories='';estimatedMinutes:number|null=null;vehicleProvisionMode:ProfessionalVehicleProvisionMode='ClientProvided';reason='';timeWindows:{dayOfWeek:number;startTime:string;endTime:string;timeZoneId:string}[]=[];readonly assignments=signal<readonly ProfessionalStudentAssignment[]>([]);readonly assignmentsLoading=signal(false);readonly assignmentDrawerOpen=signal(false);readonly selectedAssignment=signal<ProfessionalStudentAssignment|null>(null);
 private loaded:string|null=null;
 constructor(){effect(()=>{const o=this.open(),id=this.missionId();if(o){if(id&&id!==this.loaded){this.loaded=id;this.load(id);}else if(!id&&!this.loaded){this.loaded='new';this.resetCreate();}}else{this.loaded=null;this.item.set(null);this.tab.set('details');}});}
 close(){if(!this.busy())this.closeRequested.emit();}selectTab(v:'details'|'schedule'|'students'|'history'){this.tab.set(v);if(v==='students')this.loadAssignments();}

 openNewAssignment(){this.selectedAssignment.set(null);this.assignmentDrawerOpen.set(true);}
 openAssignment(a:ProfessionalStudentAssignment){this.selectedAssignment.set(a);this.assignmentDrawerOpen.set(true);}
 closeAssignmentDrawer(){this.assignmentDrawerOpen.set(false);this.selectedAssignment.set(null);}
 assignmentChanged(){this.loadAssignments();this.changed.emit();}
 private loadAssignments(){const id=this.missionId();if(!id||!this.canReadAssignments())return;this.assignmentsLoading.set(true);this.api.listProfessionalStudentAssignments(this.organizationId(),id).subscribe({next:x=>{this.assignments.set(x);this.assignmentsLoading.set(false);},error:e=>{this.formErrors.set(this.errors.getMessages(e));this.assignmentsLoading.set(false);}});}
 private resetCreate(){this.title='';this.description='';this.startsOn=this.engagementStartsOn();this.endsOn=this.engagementEndsOn();this.categories=this.defaultCategories().join(', ');this.estimatedMinutes=null;this.vehicleProvisionMode='ClientProvided';this.timeWindows=[];this.formErrors.set([]);}
 private load(id:string){this.loading.set(true);this.api.getProfessionalMission(this.organizationId(),id).subscribe({next:x=>{this.item.set(x);this.title=x.title;this.description=x.description??'';this.startsOn=x.startsOn;this.endsOn=x.endsOn;this.categories=x.teachingCategoryCodes.join(', ');this.estimatedMinutes=x.estimatedMinutes;this.vehicleProvisionMode=x.vehicleProvisionMode;this.timeWindows=x.timeWindows.map(w=>({...w}));this.loading.set(false);},error:e=>{this.formErrors.set(this.errors.getMessages(e));this.loading.set(false);}});}
 save(){const req=this.request();if(!req)return;this.busy.set(true);const id=this.missionId(),eng=this.engagementId();const call: Observable<unknown>=id?this.api.updateProfessionalMission(this.organizationId(),id,req):this.api.createProfessionalMission(this.organizationId(),eng!,req);call.subscribe({next:(r:any)=>{this.busy.set(false);this.changed.emit();if(!id&&r?.id){this.loaded=r.id;this.load(r.id);}else if(id)this.load(id);},error:(e:unknown)=>{this.busy.set(false);this.formErrors.set(this.errors.getMessages(e));}});}
 propose(){this.run(()=>this.api.proposeProfessionalMission(this.organizationId(),this.missionId()!));}activate(){this.run(()=>this.api.activateProfessionalMission(this.organizationId(),this.missionId()!));}resume(){this.run(()=>this.api.resumeProfessionalMission(this.organizationId(),this.missionId()!));}complete(){this.run(()=>this.api.completeProfessionalMission(this.organizationId(),this.missionId()!));}
 beginReason(m:'pause'|'cancel'){this.reason='';this.reasonMode.set(m);}cancelReason(){this.reasonMode.set(null);}
 addWindow(){this.timeWindows.push({dayOfWeek:1,startTime:'09:00',endTime:'12:00',timeZoneId:'Europe/Paris'});this.timeWindows=[...this.timeWindows];}
 removeWindow(index:number){this.timeWindows.splice(index,1);this.timeWindows=[...this.timeWindows];}
 confirmReason(){const r=this.reason.trim();if(r.length<2){this.formErrors.set([this.translate.instant('professionalMarketplace.missions.errors.reason')]);return;}const m=this.reasonMode();if(m==='pause')this.run(()=>this.api.pauseProfessionalMission(this.organizationId(),this.missionId()!,r));else if(m==='cancel')this.run(()=>this.api.cancelProfessionalMission(this.organizationId(),this.missionId()!,r));}
 private run(factory:()=>any){this.busy.set(true);this.formErrors.set([]);factory().subscribe({next:()=>{this.busy.set(false);this.reasonMode.set(null);this.changed.emit();this.load(this.missionId()!);},error:(e:unknown)=>{this.busy.set(false);this.formErrors.set(this.errors.getMessages(e));}});}
 private request():CreateProfessionalMissionRequest|null{const cats=this.categories.split(',').map(x=>x.trim().toUpperCase()).filter(Boolean);if(this.title.trim().length<2||!this.startsOn||!this.endsOn||cats.length===0){this.formErrors.set([this.translate.instant('professionalMarketplace.missions.errors.required')]);return null;}return{branchId:null,title:this.title.trim(),description:this.description.trim()||null,startsOn:this.startsOn,endsOn:this.endsOn,teachingCategoryCodes:cats,estimatedMinutes:this.estimatedMinutes,vehicleProvisionMode:this.vehicleProvisionMode,timeWindows:this.timeWindows.map(w=>({dayOfWeek:Number(w.dayOfWeek),startTime:w.startTime,endTime:w.endTime,timeZoneId:w.timeZoneId.trim()}))};}
}
